"""73b9377c-b83b-423e-a72d-e31e8370e1fc

Revision ID: 124828577c76
Revises: 3e131baa5a84
Create Date: 2026-05-28 02:03:41.711768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '124828577c76'
down_revision: Union[str, Sequence[str], None] = '3e131baa5a84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
