"""d4282cb9-b2ab-403f-85e7-fd312a4e1739

Revision ID: 2a34c9b5244e
Revises: ebb499c59b7c
Create Date: 2026-05-28 02:20:07.360947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a34c9b5244e'
down_revision: Union[str, Sequence[str], None] = 'ebb499c59b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
