"""e0e4b9ef-b5ad-4af7-8c4c-78f0bac19ab4

Revision ID: 3e131baa5a84
Revises: 727a5d089480
Create Date: 2026-05-28 02:00:34.536658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e131baa5a84'
down_revision: Union[str, Sequence[str], None] = '727a5d089480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
