"""359fc110-885b-42ad-8363-4f4a4bd2f9b0

Revision ID: 50623ae87bbf
Revises: f7fb22de15a9
Create Date: 2026-05-28 01:30:07.575534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50623ae87bbf'
down_revision: Union[str, Sequence[str], None] = 'f7fb22de15a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('stock_location', sa.String(), nullable=True))
    op.drop_column('products', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('products', 'stock_location')
    # ### end Alembic commands ###
