"""e3603a6f-f112-49d0-b5d5-39d0400f20d6

Revision ID: 51f8fd7e015a
Revises: 9b4f7502c701
Create Date: 2026-05-28 02:09:15.094059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f8fd7e015a'
down_revision: Union[str, Sequence[str], None] = '9b4f7502c701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
