"""04aae6a6-9bf0-41d3-a060-972fc15808a5

Revision ID: 727a5d089480
Revises: 50623ae87bbf
Create Date: 2026-05-28 01:57:16.539491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '727a5d089480'
down_revision: Union[str, Sequence[str], None] = '50623ae87bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
