"""01647467-ce1b-4df0-af33-8d7f1f11cfa7

Revision ID: 9b4f7502c701
Revises: 124828577c76
Create Date: 2026-05-28 02:04:46.398705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4f7502c701'
down_revision: Union[str, Sequence[str], None] = '124828577c76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
