"""7b2ab1cc-74ea-4b9d-8782-744caa4b191e

Revision ID: a6afc94c086c
Revises: ebcd814e602d
Create Date: 2026-05-28 02:14:31.849548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6afc94c086c'
down_revision: Union[str, Sequence[str], None] = 'ebcd814e602d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
