"""e8aa8818-36e8-42aa-8f7f-f301cfc646f7

Revision ID: d59f288156fb
Revises: 1a53e6da8f80
Create Date: 2026-05-28 01:21:14.688662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59f288156fb'
down_revision: Union[str, Sequence[str], None] = '1a53e6da8f80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
