"""246243b4-02a9-476b-88a5-e50e5e88a327

Revision ID: ebb499c59b7c
Revises: a6afc94c086c
Create Date: 2026-05-28 02:18:41.654179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb499c59b7c'
down_revision: Union[str, Sequence[str], None] = 'a6afc94c086c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
