"""a1f87cf4-6ca3-4ac8-ab3a-3581ddd86b72

Revision ID: ebcd814e602d
Revises: 51f8fd7e015a
Create Date: 2026-05-28 02:12:26.438415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcd814e602d'
down_revision: Union[str, Sequence[str], None] = '51f8fd7e015a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
