"""6b9a1442-9240-4c80-a9a5-57942f28b1f2

Revision ID: f7fb22de15a9
Revises: d59f288156fb
Create Date: 2026-05-28 01:21:23.443528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7fb22de15a9'
down_revision: Union[str, Sequence[str], None] = 'd59f288156fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
